#!/bin/sh
set -e

cat > /usr/lib/os-release << 'EOF'
PRETTY_NAME="Zyphor OS v1.9.0"
NAME="Zyphor OS GNU/Linux"
VERSION_ID="1.9.0"
VERSION="1.9.0"
VERSION_CODENAME=zyphor-os
ID=zyphor-os
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
EOF

chmod 644 /usr/lib/os-release

exit 0