#!/bin/bash
set -e

echo "Zyphor: Applying wallpapers setup..."

TARGET_DIR="/usr/share/images/desktop-base"
SRC_DIR="/usr/share/backgrounds/wallpapers-nature"

mkdir -p "$TARGET_DIR"

# safe symlinks (overwrite only if ours)
ln -sfn "$SRC_DIR/nature-1.jpg" "$TARGET_DIR/nature-1"

ln -sfn "$SRC_DIR/nature-2.jpg" "$TARGET_DIR/nature-2"

ln -sfn "$SRC_DIR/nature-3.jpg" "$TARGET_DIR/nature-3"

ln -sfn "$SRC_DIR/nature-4.jpg" "$TARGET_DIR/nature-4"

ln -sfn "$SRC_DIR/nature-5.jpg" "$TARGET_DIR/nature-5"

ln -sfn "$SRC_DIR/nature-6.jpg" "$TARGET_DIR/nature-6"

ln -sfn "$SRC_DIR/nature-7.jpg" "$TARGET_DIR/nature-7"

ln -sfn "$SRC_DIR/nature-8.jpg" "$TARGET_DIR/nature-8"

ln -sfn "$SRC_DIR/nature-9.jpg" "$TARGET_DIR/nature-9"

ln -sfn "$SRC_DIR/nature-10.jpg" "$TARGET_DIR/nature-10"

echo "Zyphor: Wallpapers configured."