#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  echo "Zyphor: Removing wallpaper symlinks..."

  # removing symlinks

  rm -f /usr/share/images/desktop-base/pragmata-1

  rm -f /usr/share/images/desktop-base/pragmata-2

  rm -f /usr/share/images/desktop-base/pragmata-3

  rm -f /usr/share/images/desktop-base/pragmata-4

  rm -f /usr/share/images/desktop-base/pragmata-5

  # removing raw files

  rm -f /usr/share/backgrounds/wallpapers-pragmata/pragmata-1.jpg

  rm -f /usr/share/backgrounds/wallpapers-pragmata/pragmata-2.jpg

  rm -f /usr/share/backgrounds/wallpapers-pragmata/pragmata-3.jpg

  rm -f /usr/share/backgrounds/wallpapers-pragmata/pragmata-4.jpg

  rm -f /usr/share/backgrounds/wallpapers-pragmata/pragmata-5.jpg

  echo "Zyphor: Cleanup done."
fi